### ISSUE TITLE
Create `RegisterSourceAssertions`

### ISSUE THREAD

**Issue by agutierrezcu** [fluentassertions/fluentassertions.autofac#12]
I think would be nice having a way to check if a specific `RegistrationSource` implementation has been registered. 

One of the most common examples could be the `OpenGenericRegistrationSource` implementation created using the registration extension method below:

```csharp
builder.RegisterGeneric(typeof(OptionsManager<>).As(typeof(IOptions<>)).SingleInstance();
```

Maybe something like:

```csharp
container.Should().Have()
         .RegisteredSource<OpenGenericRegistrationSource>()
         .ForService(typeof(IOptions<>))
         .ImplementedBy(typeof(OptionsManager<>);
```

But................ `OpenGenericRegistrationSource` is internal :(

So, a very very raw implementation could be like below:

```csharp
        ...
        GenericImplementationFor(typeof(IOptions<>), container)
                .Should()
                .Be(typeof(OptionsManager<>));
        ...

        private Type GenericImplementationFor(Type genericTypeDefinition, IContainer container)
        {
            var serviceType = genericTypeDefinition.MakeGenericType(typeof(object));
            var typedService = new TypedService(serviceType);

            var componentRegistry = container.ComponentRegistry;
            foreach (var registrationSource in componentRegistry.Sources)
            {
                var registrations = registrationSource
                    .RegistrationsFor(typedService, componentRegistry.RegistrationsFor)
                    .ToList();

                if (!registrations.Any())
                {
                    continue;
                }

                return registrations.First().Activator.LimitType.GetGenericTypeDefinition();
            }

            return null;
        }
```

**Comment by mkoertgen** [comment]
This is a good suggestion and a quite involved one, too.

As i understand, as a specific use case we would like to support testing `builder.RegisterGeneric()` which under the hood uses an `OpenGenericRegistrationSource` as can be seen from the AutoFac sources

- [OpenGenericRegistrationExtensions.cs#L51](https://github.com/autofac/Autofac/blob/4a75106b7f7dbf0d62f5452f3c3f0d58333df414/src/Autofac/Features/OpenGenerics/OpenGenericRegistrationExtensions.cs#L51)

More generally, we could as well test for registration sources and kill two birds with one stone.

As of now, we try to resemble AutoFac idioms as close as possible in the assertions, so my first bet would be to gauge `RegisterGeneric` from a register or resolve-angle, e.g.

```csharp
container.Should().Have()
    .RegisteredGeneric(typeof(OptionsManager<>)
    .As(typeof(IOptions<>)
    .SingleInstance();
```

or

```csharp
container.Should()
    .Resolve<IOptions<ConcreteType>>()
    .As<OptionsManager<ConcreteType>>();
```

Personally, i have used the generic registration idiom a few times. Until now, i never consciously/explicitly used registration sources. So i have already learned something new (Thanks ;-) ). 

I agree that support for both testing generic registrations and registration sources would be very useful to add.

What do you think about adding support one by one? 

I would tend to first adding support for `RegisterGeneric` (like documented for [Open Generic Components](http://autofaccn.readthedocs.io/en/latest/register/registration.html#open-generic-components)), then for [Registration Sources](http://autofaccn.readthedocs.io/en/latest/advanced/registration-sources.html#registration-sources). Maybe for the latter, we should try gathering some more use cases. For instance, the AutoFacs docs discuss an example with an abstract factory.

What do you think?

**Comment by agutierrezcu** [comment]
Overall, I agree with you regarding your proposed roadmap and especially when you mention
> As of now, we try to resemble AutoFac idioms as close as possible to the assertions.

I would just want to add that I would create the new assertions from a `registration` perspective and not to add any assertions from resolve-angle.

Why? `RegistrationSource` is only used if it is not found an explicit `IComponentRegistration`   in the container for the dependency trying to be resolved.

So, based on example from a resolve-angle

```csharp
container.Should()
    .Resolve<IOptions<ConcreteType>>()
    .As<OptionsManager<ConcreteType>>();
```

If your main goal is to check if a generic registration source has been actually registered, it could rise a false positive if the below code is executed as part of the registration process.

```csharp
builder
    .RegisterType<OptionsManager<ConcreteType>>()
    .As<IOptions<ConcreteType>>();
```

That's why I would only focus on design assertions from a `registration` point of view.

**Comment by mkoertgen** [comment]
Ah, i see. Thanks for pointing that out. Ok, then let's add

```csharp
container.Should().Have()
    .RegisteredGeneric(typeof(OptionsManager<>)
    .As(typeof(IOptions<>)
    .SingleInstance();
```

Would you be interested in picking this up in the next couple of days?
If not, i will try to schedule this in for the next couple of weeks.

**Comment by agutierrezcu** [comment]
Good catch @mkoertgen, I forgot to include `.Have()` as part of the fluent assertion API 
>container.Should()**.Have()**

I am going to try to create a PR with the new feature.

**Comment by mkoertgen** [comment]
One additional thought on asserting from a resolve perspective: How about resolving a generic registration for specific concrete type only known within the assertion scope?

Something like
```csharp
// assert like
container.Should().
    ResolveGeneric(typeof(TService<>))
    .AsGeneric(typeof(IService<>));

//implement something like
{
    container.Should()
        .Resolve<TService<MyPrivateDummyClass>>()
        .As<IOptionsManager<MyPrivateDummyClass>>()
}

// concrete type only known here, so no false positive possible
private class MyPrivateDummyClass {}
```

I did not think this all the way through but that's how i would probably approach assertion on generic registration in a KISS way.

What do you think? Could this work?

**Comment by agutierrezcu** [comment]
I have upgraded autofac assertions to the latest 0.6.0 version in my project and `RegisterGeneric(...)` assertion, from a registration perspective,  has worked smoothly! 

Is there still pending to create some assertions for the same purpose but from a resolving perspective?  

To be honest, I don't see it very clear so far. do you think it is worth it?

**Comment by mkoertgen** [comment]
No urgent use case coming to mind. Let's tackle it when the demand emerges.
