### ISSUE TITLE
Support for FluentAssertions 5

### ISSUE THREAD

**Issue by memark** [fluentassertions/fluentassertions.autofac#15]
Using in a project already referencing `FluentAssertions` v5 (released 2018-02-04) trying to use `fluentassertions.autofac` v0.6.0 currently gives this error:
> error CS0012: The type 'ReferenceTypeAssertions<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'FluentAssertions.Core, Version=4.19.2.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a'.

It would be great not having to downgrade. Any plans to upgrade this dependency?

**Comment by memark** [comment]
I did a little investigating. Simply updating the reference (and fixing compilation errors) doesn't really help, because there's a dependency on `NEdifis` which in turn references `FluentAssertions.Core, Version=4.11.0.0`. Trying to run the tests I then get
>Could not load file or assembly 'FluentAssertions.Core, Version=4.11.0.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a' or one of its dependencies. The system cannot find the file specified.
>   at NEdifis.Conventions.ConventionsExtensions.Check(IEnumerable`1 conventions, Type typeToTest) in C:\projects\nedifis\NEdifis\Conventions\ConventionsExtensions.cs:line 32

That project in turn seems to be a bit dead. Their latest commit was on 15 Jul 2016.

**Comment by mkoertgen** [comment]
You are right in that this project does not stride forward with the same pace and traction as does autofac or fluentassertions.

We are happily using it in about every of our dotnet project. Up  to now there was simply no need for fixing stuff adding new features.

But yes, fa5 came out just recently so  thanks for bringing this up.

I would publish an fa5-upgrade by tomorrow.

**Comment by memark** [comment]
I think you misunderstood me. By "_that_ project ... a bit dead" I'm refering to `NEdifis`! _This_ project seems much more active! And I'm obviously posting here because I like it and want to use it! 👍

**Comment by mkoertgen** [comment]
You killed two birds with a stone - we are also maintaining NEdifis ;-)
No problem. Looking into this 👍

**Comment by mkoertgen** [comment]
Should be fixed with [0.7.1](https://www.nuget.org/packages/FluentAssertions.Autofac/0.7.1). Please check.

**Comment by memark** [comment]
Works like a charm. Excellent quick work! 🥇

**Comment by mkoertgen** [comment]
You're welcome. Thanks for contributing.
