### ISSUE TITLE
Documentation speaks about NInject

### ISSUE THREAD

**Issue by memark** [fluentassertions/fluentassertions.autofac#16]
On this page https://github.com/fluentassertions/fluentassertions.autofac/blob/develop/README.md
the `Why?` paragraph speaks about `NInject`, not `Autofac`.

**Comment by mkoertgen** [comment]
Congrats. You just found a documentation glitch. I think this sneaked in when we consolidated all extensions under the fluentassertions github Organisation.
Thanks for pointing that out.
