### ISSUE TITLE
Wrong dependency version?

### ISSUE THREAD

**Issue by memark** [fluentassertions/fluentassertions.autofac#17]
1. Create a new .net 461 class library.
2. Install package FluentAssertions.Autofac 0.7.1
3. Add code
```
using Autofac;
using FluentAssertions.Autofac;

public class Test
{
    public void Test01() => new ContainerBuilder().Build().Should().Resolve<object>();
}
```
4. Compile

Compilation fails with error
`error CS1705: Assembly 'FluentAssertions.Autofac' with identity 'FluentAssertions.Autofac, Version=0.7.1.0, Culture=neutral, PublicKeyToken=null' uses 'FluentAssertions, Version=5.1.2.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a' which has a higher version than referenced assembly 'FluentAssertions' with identity 'FluentAssertions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a'`

It seems the project is referencing 5.1.2
`    <Reference Include="FluentAssertions, Version=5.1.2.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a, processorArchitecture=MSIL">
      <HintPath>..\packages\FluentAssertions.5.1.2\lib\net45\FluentAssertions.dll</HintPath>
    </Reference>`

While the nuspec only requires 5.0.0:
`<dependency id="FluentAssertions" version="[5.0.0, 6.0.0)" />`.

**Comment by memark** [comment]
There appears to be the same issue with Autofac 4.6.2 vs 4.6.0 as well.

**Comment by mkoertgen** [comment]
Hm, ok. Should change to reference as `private` or `SpecificVersion=False`.
I´ll try to get to this on this evening. Feel free to submit a PR if you're in a haste.

**Comment by mkoertgen** [comment]
Forget it. I'm already on it. ;-)

**Comment by mkoertgen** [comment]
Workaround is to just upgrade, of course. But that's user-friendly.

**Comment by mkoertgen** [comment]
Updated minimum version to the latest stable of current major.

**Comment by mkoertgen** [comment]
Please check again with 0.7.2.

**Comment by memark** [comment]
Works great, thanks!

This will ensure a smoother experience for anyone just starting with the package.
