### ISSUE TITLE
Not possible to test module with constructor parameters?

### ISSUE THREAD

**Issue by memark** [fluentassertions/fluentassertions.autofac#18]
The documentation states
```
var sut = new MyModule(...);
sut.Container(arrange: ..., types: ...)
   .Should...

sut.Builder(arrange: ..., types: ...)
```

Trying this code:
```
public class Test
{
    public void Test01()
    {
        var myModule = new MyModule(null);
        myModule.Container().Should().Resolve<object>();
    }

    public class MyModule : Autofac.Module
    {
        public MyModule(object obj)
        { }
    }
}
```

Gives compilation error
`error CS0310: 'Test.MyModule' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TModule' in the generic type or method 'TestExtensions.Container<TModule>(TModule, Action<ContainerBuilder>)'`

which is expected given the generic `new()` constaint of the method `TestExtensions.Container(...)`.

Did I misread the documentation? If not, is it still possible to test a module with constructor parameters?

**Comment by mkoertgen** [comment]
Should be a documentation glitch again.

By default, Autofac requires modules to have a parameterless ctor.
There is an idiom for testing default modules as well as modules with ctor params.
Let me look...

**Comment by mkoertgen** [comment]
Hm, you're probably right. I don't see any reason why we are constraining the extension methods with a `new()`. It seems we can omit that.

**Comment by mkoertgen** [comment]
Please check with 0.7.2

**Comment by memark** [comment]
Confirmed. This works as expected now.
