### ISSUE TITLE
Difference in resolving compared to Autofac itself

### ISSUE THREAD

**Issue by memark** [fluentassertions/fluentassertions.autofac#19]
There appears to be a difference in how this package resolves components compared to Autofac itself. I have only found it in this case with multiple registrations so far. Using version 0.7.2.
```
[Fact]
public void Test01()
{
	var containerBuilder = new ContainerBuilder();

	// First registration.
	containerBuilder.RegisterType<MyClass>();

	// "Overriding" registration.
	containerBuilder.RegisterType<MyClass>().WithParameter("obj", new object());

	var container = containerBuilder.Build();

	// Using Autofac Resolve().
	// Test succeeds.
	var actual = container.Resolve<MyClass>();
	actual.Should().NotBeNull();

	// Using FluentAssertions.Autofac Resolve()
	// Test fails.
	container.Should().Resolve<MyClass>();
}

public class MyClass
{
	public MyClass(object obj)
	{ }
}
```
This is not an uncommon scenario in my experience, e.g. first registering all types by assembly scanning, and then "overriding" the ones who need extra parameters (or other special cares).

**Comment by memark** [comment]
I did some investigating, and I think I might have found the issue.

On this line
https://github.com/fluentassertions/fluentassertions.autofac/blob/717b8f114f489730ad2834fb2b69aea007757571/Shared/ResolveAssertions.cs#L41

it appears a "normal" single resolve of type `T` is in fact carried out as resolve of `IEnumerable<T>`. Which, given Autofac semantics, returns an array of all relevant registrations. And one of them fails in this case.

I'm not sure what the reason is for converting the resolve assertions in this way, but it does seem a bit dangerous to me.

**Comment by mkoertgen** [comment]
I was not aware that AutoFac resolves differently in this case.

Actually, i was not aware that registering the same type multiple times could be a worthwhile use case for testing.

But yes, first scanning and then overriding sounds like a common thing todo.

I think resolving the assertions this way was just the most generic fashion on the Container.

**Comment by mkoertgen** [comment]
Interesting. What would be the goal of such a test?

Asserting a module registers both ways? Or resolves both ways?

I would tend to think of that as some kind of  di integration test.

**Comment by memark** [comment]
Sorry if I was unclear here. I'm not using such a test case for any goal. I just put it up here to show the difference in behaviour.

The actual use case here is that I was converting my old tests, using manual Autofac resolve, to using this package. Without having changed anything else, some of my tests suddenly started failing.

**Comment by mkoertgen** [comment]
Great investigation though. We try to resemble Autofac as closely as possible. So addressing this should be a good thing to do.

I would tend to address this as a bug rather than a feature ;-). Let me know if you would be interested in contributing, btw.

Thanks, Marcel.

**Comment by memark** [comment]
I would be interested. PRing is always fun!

**Comment by mkoertgen** [comment]
Great to here that. Feel free to add a test and optionally an implementation if you like.
Until this evening i won't have any spare time to join.

**Comment by memark** [comment]
I've started to look into it. It seems the IEnumerable is used to get an empty array instead of an exception, and then to use a normal assert on that (possibly empty) array. I suppose there are two ways forward:
* using ordinary Resolve() and catching that exception
* using ResolveOptional() and kinda keep the same logic (i've tried, but ran into some problem with the assembly scanning tests. not sure how it's related.)

I'll have another look in a few days' time.

**Comment by mkoertgen** [comment]
Looking at your example again. Did you try adding a limit type using `As<TLimit>()`.

I think this might cause an empty resolve array, cf. Autofac best practice:
- http://autofac.readthedocs.io/en/latest/best-practices/index.html#use-as-t-in-delegate-registrations

**Comment by memark** [comment]
I'm not sure I can see how that is related. Where do you suggest I add such a call?
IMHO it should not make any difference, the issue is the double registration, regardless of whether it's made with `MyClass` or `IMyClass` as its service type.

Looking at the provided link, the section that falls most closely to what I'm doing is probably https://autofac.readthedocs.io/en/latest/best-practices/index.html#register-components-from-least-to-most-specific, even if no configuration file is involved in this case.

**Comment by mkoertgen** [comment]
In your test try adding `AsSelf()` etc.

```csharp
containerBuilder.RegisterType<MyClass>().AsSelf();
```

This should fix the tests w.r.t to `FluentAssertions.Autofac`. 

However, this is a workaround as you correctly pointed out. The Autofac docs introduce registration by type in fact without an `.As...`, cf.:

- https://autofac.readthedocs.io/en/latest/register/registration.html#register-by-type

**Comment by memark** [comment]
I'm sorry, but I probably won't finish this. The project I'm working on has taken another direction, and we are now resolving all public types via Xunit MemberData instead.

**Comment by mkoertgen** [comment]
Ok, closing this for now. Thanks for contributing.
