### ISSUE TITLE
Strong-name sign so that delay-signed projects can be executed.

### ISSUE THREAD

**Issue by l3a0** [fluentassertions/fluentassertions.autofac#20]
System.IO.FileLoadException
Could not load file or assembly 'FluentAssertions.Autofac, Version=0.7.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
   at My.ComponentTests.Lib.ShouldFooBar()

**Comment by mkoertgen** [comment]
Are you absolutely certain you need strong name signing? There may be legacy use cases for produtction. But is it necessary in a test project?

We abandonded from strong name signing some time ago, cf.:
- https://github.com/awesome-inc/FontAwesome.Sharp/issues/9

**Comment by l3a0** [comment]
Our assembly is delay signed because it is consumed in projects that require strong named assemblies. Our assembly has internal classes that we wish to expose to unit tests, which requires the unit tests to be strong named as well. We can bypass this by making the classes public. We can also look into delay signing via a separate build step. Thanks for the insights.

**Comment by mkoertgen** [comment]
Ok, that would make a point.
