### ISSUE TITLE
Target to .net 4.7.2

### ISSUE THREAD

**Issue by agutierrezcu** [fluentassertions/fluentassertions.autofac#21]
Is there any change to make the nuget multitargeting and add assemblies for .net framework 4.7.2? 

Or, it might be a simpler solution, make the project targeting to the latest .net framework version (4.7.2).

I have made some preliminaries tests and everything compiles and works as expected. (Unit testing in green).

**Comment by mkoertgen** [comment]
Targeting 4.7.2 should work out of the box in the CI build environment _vs2017_:

- https://github.com/fluentassertions/fluentassertions.autofac/blob/develop/appveyor.yml#L2
- https://www.appveyor.com/docs/build-environment/#net-framework

Feel free to submit a PR. I'll be happy to merge it in :+1:

**Comment by mkoertgen** [comment]
I just began streamlining the projects using multi-targeting. We should get net47-support as a byproduct of this ;-)

**Comment by mkoertgen** [comment]
@agutierrezcu Checkout [0.7.3](https://www.nuget.org/packages/FluentAssertions.Autofac/0.7.3)
