### ISSUE TITLE
Container.Should().Have() Is not found.

### ISSUE THREAD

**Issue by stephenpatten** [fluentassertions/fluentassertions.autofac#24]
This one must be super simple but for whatever reason this extension method is bombing on me, as in I'm unable to compile the test project once I have included a test that uses the Have() extension.

My project is 2017 Enterprise MSTest (4.5.2) and I have been successful at using Fluent Validation in other tests in the same project.  

The Should extension in the failing to compile test is of type Primitives, and when I F-12 this is returned

    /// <summary>
    /// Returns an <see cref="T:FluentAssertions.Primitives.ObjectAssertions" /> object that can be used to assert the
    /// current <see cref="T:System.Object" />.
    /// </summary>
    [Pure]
    public static ObjectAssertions Should(this object actualValue)
    {
      return new ObjectAssertions(actualValue);
    }

I believe that the Should extension should be hanging off of IContainer, right?

Any help would be appreciated.

-Stephen

**Comment by mkoertgen** [comment]
Hi @stephenpatten, 
You're right. It looks like the compiler can only resolve the FluentAssertions core extensions but not the AutoFac-specific ones. Note that they live in the namespace `FluentAssertions.AutoFac`.

Be sure to add `using FluentAssertions.Autofac;` after `using FluentAssertions;` at the top of your Test classes to help the compiler find the IContainer-extension methods.

Let me know if that helps.

**Comment by stephenpatten** [comment]
Thanks for the quick response. 

As a sanity check I have forked FluentAssertions.Autofac  and can get the repo to build on the same machine that is having issues with adding the reference to fluentAssertions.Autofac. Here are some images that might help use diagnose the issue. The UnitTest project is targeting 4.5.2


![snap770](https://user-images.githubusercontent.com/354728/47016103-9cc40800-d103-11e8-9428-e7f364d1a4aa.png)

![snap771](https://user-images.githubusercontent.com/354728/47016114-a2215280-d103-11e8-8014-e573ae568a4a.png)

**Comment by mkoertgen** [comment]
Hm, i would need to guess. The indicated versions should be compatible. 

Looks like something simple & stupid. It seems the package reference somehow got messed up. 

However, 4.5.2 should be ok. Did you probably tweak the target framework after adding the NuGet reference?

Did you try building with maximum verbosity and check the output on messages with respect to the reference?

If that does not help, would it be possible for you to publish the solution in a manner that i could possibly reproduce the error?

**Comment by stephenpatten** [comment]
How can I give it to you in a secure way?

**Comment by stephenpatten** [comment]
Setting the build output did not shed any light on the issue, BUT if I removed the nuget package for the test project and then added the dll by hand it works... weird

**Comment by mkoertgen** [comment]
For me to reproduce you could clone/upload it to a private repo and add me as a team member. GitLab.com has free private/personal repos, for instance.

Another guess: Did you try moving the using clauses out of your own namespace and to the top of file?

**Comment by stephenpatten** [comment]
Promise I will get to this as soon as I get settled into my new house and job (sort of).

**Comment by mkoertgen** [comment]
Close due to inactivity
