### ISSUE TITLE
Update coveralls

### ISSUE THREAD

**Issue by mkoertgen** [fluentassertions/fluentassertions.autofac#25]
Hi @dennisdoomen i realized that the coveralls connection got stale after moving to the repo over to the fluentassertions github org. Any objections on granting app access?

**Comment by dennisdoomen** [comment]
Oh, that's where that request came from. Sure, just re-request access.

**Comment by mkoertgen** [comment]
Great. Thanks. Sorry for bothering on the weekend.

**Comment by dennisdoomen** [comment]
No worries. The weekends and evenings is the time I _can_ work on open-source.
