### ISSUE TITLE
Migrate from cake to nuke

### ISSUE THREAD

**Issue by mkoertgen** [fluentassertions/fluentassertions.autofac#28]
After reading @dennisdoomen blog post [14 reasons for adopting Nuke as your next build automation tool](https://www.continuousimprover.com/2020/03/reasons-for-adopting-nuke.html) we adopted [nuke](https://github.com/nuke-build/nuke) in some projects recently. So far the experience has been great and we can't think of any solid reasons to stay with [Cake](https://github.com/cake-build/cake).

Here is some context:

- libhunt: [NUKE vs Cake](https://dotnet.libhunt.com/compare-nuke-vs-cake)
- [You don’t need Cake anymore; the way to build .NET projects going forward.](https://pknopf.com/post/2019-03-10-you-dont-need-cake-anymore-the-way-to-build-dotnet-projects-going-forward/)
- [14 reasons for adopting Nuke as your next build automation tool](https://www.continuousimprover.com/2020/03/reasons-for-adopting-nuke.html)

**Comment by matkoch** [comment]
Let me know when you need help.

**Comment by mkoertgen** [comment]
Hi @matkoch, that's so nice. Thank you! 

Right now, it's mostly my lack of free time holding me back to tackle this. 
If you have some spare time i would love to accept a PR on this.

Best regards
