### ISSUE TITLE
Support Autofac 6

### ISSUE THREAD

**Issue by mkoertgen** [fluentassertions/fluentassertions.autofac#31]

**Comment by Callindrill** [comment]
Is there an update for when this would go out as a package that's available for consumption?

**Comment by mkoertgen** [comment]
Hi @Callindrill ,
Thanks for reaching out. Up to now nobody asked for or was in need of this. 

We are currently short of spare time to tackle this and thus open for contributions (PRs).

Main blocker is that AutoFac 6 privatized the module registration on the ContainerBuilder for which we need a different approach.

Will get back to you later this day.

**Comment by Callindrill** [comment]
Sounds great! I will also reach out to my team and see if we have capacity for getting a PR in. Anything you can do to help point us (or anyone else) in the right direction would be greatly appreciated. Thanks!

**Comment by mkoertgen** [comment]
Hi @Callindrill ,

Looked into this. Seems as support for Autofac 6 is already implemented. 

Usually we prefer streamlining releases with parent package [FluentAssertions](https://github.com/fluentassertions/fluentassertions).
- current stable is `5.10.3`, 
- latest prerelease seems to be `6.0.0-alpha002`

I could release a `5.11.0` or a prelease as well. 

@dennisdoomen Do we plan to publish releases after 5.10.x? Or is it already going for the 6.0.x?

**Comment by dennisdoomen** [comment]
Unless somebody reports a critical bug, most likely it's going to be 6.0.0.

**Comment by mkoertgen** [comment]
Great. Thanks for the quick response @dennisdoomen. 

@Callindrill Then I will go for the 5.11.0 in the next few days. 
Let me know in case you would be interested in a 6-prerelease as well.

**Comment by mkoertgen** [comment]
Hi @Callindrill ,

Have a look at: https://www.nuget.org/packages/FluentAssertions.Autofac/5.11.0

**Comment by Callindrill** [comment]
Will do, thanks!
