### ISSUE TITLE
If you use RegisteredGeneric and Named you can't test it 

### ISSUE THREAD

**Issue by silviatosi** [fluentassertions/fluentassertions.autofac#32]
Hi,

it would be nice to test if my generic registration has been successfully registered with the given name - as per following example

// PRODUCTION CODE 
builder.RegisterGeneric(typeof(MyGenericTreeClass<>))
           .Named("TreeImplementation", typeof(IMyGenericInterface<>))
           .InstancePerDependency();
           
// WHAT COULD BE NICE TO HAVE AS TEST CODE 
container.Should().Have().RegisteredGeneric(typeof(MyGenericTreeClass<>))
           .Named("TreeImplementation", typeof(IMyGenericInterface<>))
           .InstancePerDependency();

// WHAT I REALLY HAVE AS TEST CODE
container.Should().Have().RegisteredGeneric(typeof(MyGenericTreeClass<>));

Maybe am I missing something ? 

Thank you very much,
Silvia

**Comment by mkoertgen** [comment]
Hi @silviatosi ,

Currently, the way to test is exactly the one you showed (without asserting on the name).
Testing for named registration would be a good enhancement. Thanks for the suggestion.

Would you be open for submitting a pull request on this?

**Comment by silviatosi** [comment]
Hi @mkoertgen 
I would really like to work on it - just I am not sure I am capable of - but I will have a look this night at the implementation of named and keyed registration and I will answer you. 
It would be a really "nice to have" :)

**Comment by mkoertgen** [comment]
Thanks, sounds good to me. I pinned it towards the v6 release together with the parent project FluentAssertions.

**Comment by mkoertgen** [comment]
Added in 6.5.1
