### ISSUE TITLE
Remove NUnit and NSubstitue dependencies from shipped assembly

### ISSUE THREAD

**Issue by kevinkuszyk** [fluentassertions/fluentassertions.autofac#5]
Hey @mkoertgen!

I just tried out this package on a new project and hit a blocker - there seems to be a dependency on NUnit in the shipped assembly:

```
System.IO.FileLoadException : Could not load file or assembly 'nunit.framework, Version=3.0.5813.39031, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at FluentAssertions.Autofac.ResolveAssertions`1..ctor(IContainer container)
   at FluentAssertions.Autofac.ContainerAssertions.Resolve[TService]()
```

I also noticed the NuGet package has a dependency on NSubstitute.

I think this is caused because you have tests alongside production code in the same project.  Before I put the effort in, would you accept a PR that splits tests and production code into separate projects?

**Comment by mkoertgen** [comment]
Hi @kevinkuszyk. Thanks for trying out and bringing this up.

Sure, separating into a test project is what most people do. If possible, i would prefer to keep tests alongside, however. 

There should be no public code that relies on the test dependencies like NUnit. But in fact, i found one single hard NUnit dependency here

https://github.com/awesome-inc/FluentAssertions.Autofac/blob/develop/Shared/ResolveAssertions.cs#L22

This uses the [AssertionException](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Exceptions/AssertionException.cs) from NUnit.

Having said that, we would of course accept a PR splitting projects but would prefer a more compact PR changing that to `Execute.AssertionScope` which is how asserts should be done according to FluentAssertions, i.e. replacing

```
throw new AssertionException(...) // NUnit!
```

with something like

```
Execute.Assertion
            .ForCondition(_instances.Any())
            .BecauseOf(...)
            .FailWith("Expected container to resolve '{typeof(TService)}', Subject);
```

**Comment by mkoertgen** [comment]
Maybe it is even simpler to just use

```
_instances.Should().NotBeEmpty(...)
```

I'm on it

**Comment by mkoertgen** [comment]
@kevinkuszyk I comitted something to fix the NUnit issue. Does the [0.2.3-version](https://www.nuget.org/packages/FluentAssertions.Autofac/0.2.3) work for you?

**Comment by kevinkuszyk** [comment]
Thanks - you beat me to it.  I pushed some code yesterday and was going to send a PR this morning!

Yes, that's fixed it for me.

The nuspec also lists a dependency on NSubstitute.  I don't think you need that either, so maybe consider removing it too?

Thanks again!

**Comment by mkoertgen** [comment]
Sorry for duplicating the effort. Next time, just comment with something like "I'm on it".

Do you think the dependency on NSubstitute might hit you in any way? 

Actually, NSubstitute is used to inject/substitute external dependencies of a module. A typical example are cross-cutting services that are registered somewhere else, e.g. another module.

For an example see [TestExtensions_Should.cs#L42](https://github.com/awesome-inc/FluentAssertions.Autofac/blob/develop/FluentAssertions.Autofac.Net45/TestExtensions_Should.cs#L42)

You are right that this introduces another dependency for just the little gain of some syntactic sugar that simplifies setting up module testing with external types. A user could as well just use the arrange action to set up  the external dependencies. That is, replacing

```
Module<MyModule>.GetTestContainer(types:new[] {typeof (ICrossCuttingService)});
```

with

```
Module<MyModule>.GetTestContainer(builder =>{
    builder.RegisterInstance(Substitute.For<ICrossCuttingService>());
});
```

**Comment by mkoertgen** [comment]
I discussed this with @ThomasMentzel. Yeah, we will remove the NSubstitute dependency as well since the gain is too low as this may clash with other isolation frameworks out ther.

**Comment by mkoertgen** [comment]
@kevinkuszyk Just updated to [0.2.4](https://www.nuget.org/packages/FluentAssertions.Autofac/0.2.4) which also removed the NSubstitute dependency. Please have a look. 

If ok, we can close the issue.

**Comment by kevinkuszyk** [comment]
> Sorry for duplicating the effort. Next time, just comment with something like "I'm on it".

No problem - I had a few minutes before I left the office, so I just copy and pasted your suggested code across.

 Version 0.2.4 is working for me, and looking much better without that NSub dependency.
