### ISSUE TITLE
Reference issue nuget package for FluentAssertions.Autofac 0.3.0

### ISSUE THREAD

**Issue by NeilCross** [fluentassertions/fluentassertions.autofac#6]
In the latest release, the nuspec defines a dependency for FluentAssertions 4.2.2, however the library is currently built against 4.10.0, causing VS to complain about 

Assembly 'FluentAssertions.Autofac' with identity 'FluentAssertions.Autofac, Version=0.3.0.0, Culture=neutral, PublicKeyToken=null' uses 'FluentAssertions.Core, Version=4.10.0.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a' which has a higher version than referenced assembly 'FluentAssertions.Core' with identity 'FluentAssertions.Core, Version=4.2.2.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a'

Adding a referencing to FluentAssertions 4.10.0 directly causes this problem to be resolved.

**Comment by mkoertgen** [comment]
Do you need to be backwards compatible to 4.2.x which mean re-referencing? Or can we just update the minimum version in the .nuspec?
- [FluentAssertions.Autofac.NuGet/Package.nuspec#L19](https://github.com/awesome-inc/FluentAssertions.Autofac/blob/develop/FluentAssertions.Autofac.NuGet/Package.nuspec#L19)

**Comment by NeilCross** [comment]
Personally I don't need it to be backwards compatible; updating the version in the nuspec file would be the way to go.

**Comment by mkoertgen** [comment]
@NeilCross done with https://github.com/awesome-inc/FluentAssertions.Autofac/commit/6914bdffa8b77afe13497bc529c689d0948cde01. Thanks for checking out.

**Comment by mkoertgen** [comment]
Updated to 4.11 with https://github.com/awesome-inc/FluentAssertions.Autofac/commit/a85fe7d0561732aabb9e4af9cf2f29412d2522c2.

Fixed in [0.3.2](https://www.nuget.org/packages/FluentAssertions.Autofac/0.3.2).

**Comment by mkoertgen** [comment]
@NeilCross Thanks for checking out & contributing the issue. Much appreciated.

**Comment by NeilCross** [comment]
No probs, thanks for the quick resolution.
