### ISSUE TITLE
Support of .net core

### ISSUE THREAD

**Issue by RufusJWB** [fluentassertions/fluentassertions.autofac#8]
Please consider supporting .net core also. Right now I get the following exception, when trying to use FluentAssertion.Autofac with a .net core application:

>       Package FluentAssertions.Autofac 0.3.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package FluentAssertions.Autofac 0.3.2 supports: net45 (.NETFramework,Version=v4.5)
>       One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by mkoertgen** [comment]
Great enhancement. We should follow the parent project FluentAssertions with this.
Right now, i am short in spare time so it may take some weeks for me to handle this myself. 
Pull requests are welcome, though. So feel free to get going. Shout out if you need guidance.

@ThomasMentzel

**Comment by mkoertgen** [comment]
There was much chat in the FluentAssertions gitter chatroom  about moving to .net core.
Personally, i would love to wait until the net core 2.0 release, cf. [.NET Core Roadmap](https://github.com/dotnet/core/blob/master/roadmap.md)

**Comment by mkoertgen** [comment]
@RufusJWB I'm looking into it. I am updating some dependencies along the way. Ok for you to target AutoFac 4+ ?

**Comment by RufusJWB** [comment]
Thank you for taking up this topic. I'm using Autofac 4.6.0 together with Autofac.Extras.Moq 4.1.0-rc5-246.

It would be great if you would be able to support netcoreapp1.0, since the application I'm testing is deployed to Amazon Lambda which only supports .netcoreapp1.0. Technically, I could have the test project targeting also .netcoreapp1.1, but I would like to have both projects on the same framework if possible.

**Comment by RufusJWB** [comment]
As soon as you have an alpha available I'll be more than happy to test ist. I would have done it by myself, but I've never developed a Nuget package.

**Comment by mkoertgen** [comment]
@RufusJWB Feel free to check out the [0.4.0-beta](https://www.nuget.org/packages/FluentAssertions.Autofac/0.4.0-beta0001). It targets `netstandard1.6` and should be fine with `netcoreapp1.0`.

**Comment by RufusJWB** [comment]
@mkoertgen Works like a charm :-) Thank you very much! I really appreciate this!

**Comment by mkoertgen** [comment]
Merged to master. Stable 0.4.0 is available now

**Comment by RufusJWB** [comment]
Thank you!
