### ISSUE TITLE
Interceptor and parameter registrations

### ISSUE THREAD

**Issue by Caleb9** [fluentassertions/fluentassertions.autofac#9]
First of all, an awesome library, so thanks for the efforts :).

I have a question though: would it at all be possible to assert `WithParameter(s)` and `InterceptedBy` registrations? As far as I can tell it is not right now, is it? It would be an extremely useful feature for more complex scenarios with a lot of decorators etc. but I have no idea if it is doable.

**Comment by mkoertgen** [comment]
Hi caleb, thanks for your suggestion.

@Caleb9 i added some prototype code for "WithParameter" on develop branch, commit 069358196fb46781f8252bf14d3573ad38b6228c.

Let me know if this goes into the direction you had in mind.

**Comment by mkoertgen** [comment]
asserting on interceptors would need to depend on autofac extras dynamicproxy/2, right?

I would suggest to put this in a separate package, then. This should be aware of reference change from dynamicproxy2  (autofac < 4) to dynamicproxy (autofac >= 4)

**Comment by Caleb9** [comment]
> @Caleb9 i added some prototype code for "WithParameter" on develop branch, commit 0693581.
>
> Let me know if this goes into the direction you had in mind.

Definitely yes! Additionally if it would support lambda syntax it would be even better. Something like
```
    public RegistrationAssertions WithParameter(Func<Parameter, bool> predicate)
    {
        var matchingParams = _parameters.Where(predicate);
        // TODO
        return this;
    }
```
I didn't have time to get into your code enough to be able to do the "TODO" part myself ;).

Anyway then the usage could be for example `.WithParameter(p => p is ResolvedParameter)` and any further conditions you'd like the parameter to fulfill. What do you think?

> asserting on interceptors would need to depend on autofac extras dynamicproxy/2, right?
>
> I would suggest to put this in a separate package, then.

You're right, I forgot interceptors are provided by a separate package.

**Comment by Caleb9** [comment]
I've implemented it as I think it could work in #10, so please review it and see if this is the right direction.

**Comment by mkoertgen** [comment]
Looks good. Merged your changes into develop and master. Version 0.5.1 should contain your changes.

Would close this issue if no objections.

**Comment by Caleb9** [comment]
Nice, thanks. No objections. :)
